-- Inserção de dados na tabela 'tb_category'
INSERT INTO tb_category (name) VALUES ('Electronics');
INSERT INTO tb_category (name) VALUES ('Fashion');
INSERT INTO tb_category (name) VALUES ('Sports');
INSERT INTO tb_category (name) VALUES ('Books');
INSERT INTO tb_category (name) VALUES ('Home');
INSERT INTO tb_category (name) VALUES ('Automotive');
INSERT INTO tb_category (name) VALUES ('Kids');
INSERT INTO tb_category (name) VALUES ('Health');
INSERT INTO tb_category (name) VALUES ('Toys');
INSERT INTO tb_category (name) VALUES ('Tools');
INSERT INTO tb_category (name) VALUES ('Food');
INSERT INTO tb_category (name) VALUES ('Furniture');
INSERT INTO tb_category (name) VALUES ('Instruments');
INSERT INTO tb_category (name) VALUES ('Cameras');
INSERT INTO tb_category (name) VALUES ('Computers');
INSERT INTO tb_category (name) VALUES ('Phones');
INSERT INTO tb_category (name) VALUES ('Art');
INSERT INTO tb_category (name) VALUES ('Jewelry');
INSERT INTO tb_category (name) VALUES ('Power Tools');
INSERT INTO tb_category (name) VALUES ('Exercise Equipment');
INSERT INTO tb_category (name) VALUES ('Movies');
INSERT INTO tb_category (name) VALUES ('Sportswear');
INSERT INTO tb_category (name) VALUES ('Pet Accessories');
INSERT INTO tb_category (name) VALUES ('Writing Instruments');
INSERT INTO tb_category (name) VALUES ('Footwear');
INSERT INTO tb_category (name) VALUES ('Bags');
INSERT INTO tb_category (name) VALUES ('Office Supplies');
INSERT INTO tb_category (name) VALUES ('Home Care');
INSERT INTO tb_category (name) VALUES ('Cleaning Products');
INSERT INTO tb_category (name) VALUES ('Camping Equipment');
INSERT INTO tb_category (name) VALUES ('Party Supplies');
INSERT INTO tb_category (name) VALUES ('Wind Instruments');
INSERT INTO tb_category (name) VALUES ('Cell Phone Accessories');
INSERT INTO tb_category (name) VALUES ('Party Decorations');
INSERT INTO tb_category (name) VALUES ('Stationery Products');
INSERT INTO tb_category (name) VALUES ('DJ Equipment');
INSERT INTO tb_category (name) VALUES ('Headphones');
INSERT INTO tb_category (name) VALUES ('Camera Lenses');
INSERT INTO tb_category (name) VALUES ('Perfumes');
INSERT INTO tb_category (name) VALUES ('Lighting');
INSERT INTO tb_category (name) VALUES ('Personal Care Products');
INSERT INTO tb_category (name) VALUES ('Security Cameras');
INSERT INTO tb_category (name) VALUES ('Appliances');
INSERT INTO tb_category (name) VALUES ('Kitchen Utensils');
INSERT INTO tb_category (name) VALUES ('Beers and Wines');
INSERT INTO tb_category (name) VALUES ('Collectibles');
INSERT INTO tb_category (name) VALUES ('Fishing Equipment');
INSERT INTO tb_category (name) VALUES ('Wall Clocks');
INSERT INTO tb_category (name) VALUES ('Bathroom Accessories');
INSERT INTO tb_category (name) VALUES ('Travel Accessories');
INSERT INTO tb_category (name) VALUES ('Swimming Equipment');
INSERT INTO tb_category (name) VALUES ('Swimwear');
INSERT INTO tb_category (name) VALUES ('Gardening Equipment');
INSERT INTO tb_category (name) VALUES ('String Instruments');
INSERT INTO tb_category (name) VALUES ('Bicycle Accessories');
INSERT INTO tb_category (name) VALUES ('Underwear');
INSERT INTO tb_category (name) VALUES ('Hair Accessories');
INSERT INTO tb_category (name) VALUES ('Paintings and Frames');
INSERT INTO tb_category (name) VALUES ('Office Furniture');
INSERT INTO tb_category (name) VALUES ('Hair Products');
INSERT INTO tb_category (name) VALUES ('Climbing Equipment');
INSERT INTO tb_category (name) VALUES ('Car Accessories');
INSERT INTO tb_category (name) VALUES ('Percussion Instruments');
INSERT INTO tb_category (name) VALUES ('Winter Clothes');
INSERT INTO tb_category (name) VALUES ('Fishing Gear');
INSERT INTO tb_category (name) VALUES ('Athletic Shoes');
INSERT INTO tb_category (name) VALUES ('Air Purifiers');
INSERT INTO tb_category (name) VALUES ('Camping Gear');

-- Adicione mais linhas conforme necessário
